package com.tres.network.packet.protocol;

public enum ProtocolIds {
	UNKNOWN(-1),
	TEXT_PACKET(1),
	DISCONNECT_PACKET(2),
	ALIVE_SIGNAL_PACKET(3),
	LOGIN_STATUS_PACKET(4),
	LOGIN_PACKET(5),
	CLIENT_INFO_PACKET(6),
	PLAYER_INITIALIZED_PACKET(7),
	PLAYER_INFO_REQUEST_PACKET(8),
	GAME_EVENT_PACKET(9),
	GAME_LEVEL_PACKET(10),
	ADD_PLAYER_PACKET(11),
	CARD_TRANSACTION_PACKET(12),
	REQUEST_AVAILABLE_GAMES_PACKET(13),
	AVAILABLE_GAMES_PACKET(14),
	PLAYER_ACTION_PACKET(15),
	PLAYER_ACTION_RESPONSE_PACKET(16),
	SERVER_TO_CLIENT_HANDSHAKE_PACKET(17),
	CLIENT_TO_SERVER_HANDSHAKE_PACKET(18),
	CARD_LIST_PACKET(19),
	GAME_RESULT_PACKET(20),
	PLAYER_GAME_ACTION_PACKET(21),
	FILE_CHUNK_DATA_PACKET(22),
	FILE_CHUNK_STREAM_PACKET(23),
	FILE_CHUNK_STREAM_RESPONSE_PACKET(24),
	FILE_STREAM_REQUEST_PACKET(25),
	FILE_STREAM_RESULT_PACKET(26),
	REMOVE_PLAYER_PACKET(27);

	public static final int PROTOCOL = 13;

	public static final int VERSION = 0;

	public final int id;

	ProtocolIds(int id) {
		this.id = id;
	}
}
